# Generated by Django 2.2.7 on 2019-12-20 15:52

from django.db import migrations, models
import transactions.models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='account_number',
            field=models.CharField(default='5183938987', editable=False, max_length=10, validators=[transactions.models.validate_account_number]),
        ),
    ]
