# Generated by Django 2.2.7 on 2019-11-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_transaction_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
