# Generated by Django 2.2.7 on 2019-11-23 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
