# Generated by Django 2.2.7 on 2019-11-23 16:29

from django.db import migrations, models
import transactions.models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_client_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='account_number',
            field=models.CharField(max_length=10, validators=[transactions.models.validate_account_number]),
        ),
    ]
