# Generated by Django 2.2.7 on 2019-11-24 15:40

from django.db import migrations, models
import transactions.models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_auto_20191124_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='account_number',
            field=models.CharField(default='1000084012', editable=False, max_length=10, validators=[transactions.models.validate_account_number]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.PositiveIntegerField(),
        ),
    ]
