var child = [
  { 'dupe': false, 'type': 4, 'name': 'accounts', 'dir': 'c0', 'linked': 5, 'url': 'http://127.0.0.1:8000/accounts/', 'fetched': true, 'code': 404, 'len': 4092, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': '[none]', 'missing': true, 'csens': true, 'child_cnt': 5, 'issue_cnt': [ 6, 0, 0, 4, 0 ], 'sig': 0xfe0f7ffe },
  { 'dupe': false, 'type': 4, 'name': 'login', 'dir': 'c1', 'linked': 5, 'url': 'http://127.0.0.1:8000/login/', 'fetched': true, 'code': 200, 'len': 3847, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 3, 'issue_cnt': [ 1, 0, 0, 4, 0 ], 'sig': 0x8c24a451 },
  { 'dupe': false, 'type': 4, 'name': 'logout', 'dir': 'c2', 'linked': 2, 'url': 'http://127.0.0.1:8000/logout/', 'fetched': true, 'code': 200, 'len': 2155, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 4, 0 ], 'sig': 0xe9fe3914 },
  { 'dupe': false, 'type': 4, 'name': 'password-reset', 'dir': 'c3', 'linked': 5, 'url': 'http://127.0.0.1:8000/password-reset/', 'fetched': true, 'code': 200, 'len': 3261, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': true, 'child_cnt': 3, 'issue_cnt': [ 0, 1, 1, 8, 0 ], 'sig': 0xdb4db2a0 },
  { 'dupe': false, 'type': 4, 'name': 'password-reset', 'dir': 'c4', 'linked': 2, 'url': 'http://127.0.0.1:8000/password-reset/', 'fetched': true, 'code': 200, 'len': 2779, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 1, 4, 0 ], 'sig': 0xe6871d14 },
  { 'dupe': false, 'type': 4, 'name': 'register', 'dir': 'c7', 'linked': 5, 'url': 'http://127.0.0.1:8000/register/', 'fetched': true, 'code': 200, 'len': 4922, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 5, 'issue_cnt': [ 2, 0, 0, 6, 0 ], 'sig': 0x1b359b93 },
  { 'dupe': false, 'type': 4, 'name': 'transaction_history', 'dir': 'c8', 'linked': 2, 'url': 'http://127.0.0.1:8000/transaction_history/', 'fetched': true, 'code': 200, 'len': 3690, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 1, 0, 4, 0 ], 'sig': 0xe6848b54 },
  { 'dupe': false, 'type': 4, 'name': 'transaction_history', 'dir': 'c9', 'linked': 2, 'url': 'http://127.0.0.1:8000/transaction_history/', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfffbffff },
  { 'dupe': false, 'type': 4, 'name': 'transaction_new', 'dir': 'c12', 'linked': 5, 'url': 'http://127.0.0.1:8000/transaction_new/', 'fetched': true, 'code': 200, 'len': 3533, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 4, 'issue_cnt': [ 0, 1, 1, 4, 0 ], 'sig': 0x6cec58eb },
  { 'dupe': true, 'type': 4, 'name': 'transaction_new', 'dir': 'c13', 'linked': 2, 'url': 'http://127.0.0.1:8000/transaction_new/', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfffbffff },
];
