# Generated by Django 2.2.7 on 2019-11-24 15:13

from django.db import migrations, models
import transactions.models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_auto_20191123_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='account_number',
            field=models.CharField(default='3870034723', editable=False, max_length=10, validators=[transactions.models.validate_account_number]),
        ),
    ]
